### ISSUE TITLE
xcodebuild not found in docker

### ISSUE THREAD

**Issue by rizkyyangpalsu** [vinivendra/Gryphon#130]
I've been using Gryphon using Docker. But I have error
![image](https://github.com/vinivendra/Gryphon/assets/25103643/72bff500-a903-4dde-b6f2-925e23bf5fed)

There is have solution for this?

**Comment by vinivendra** [comment]
Hey @rizkyyangpalsu, the Docker image is based on Ubuntu, which doesn’t have Xcode (or xcodebuild). What command did you run to get this error? If you were trying to do something that didn’t depend on Xcode, please let us know.

**Comment by rizkyyangpalsu** [comment]
I have modified the docker using docker compose and then I run the gryphon to init the existing project like this:

![image](https://github.com/vinivendra/Gryphon/assets/25103643/dab5a1a2-237c-4662-bb8e-78ff7dcf3dcf)

I don't have any idea for this. Thank you

**Comment by vinivendra** [comment]
Yeah, thats the problem. You’re trying to initialize an Xcode project, which requires Xcode’s tools, in a Ubuntu-based Docker image (which doesn’t have Xcode tools since there’s no Xcode on Ubuntu).
Your best bet is to either translate your files manually via command line (without Xcode integration) or to help us make Gryphon support Swift 5.8 (#127) so you can use Xcode tools on macOS.

**Comment by rizkyyangpalsu** [comment]
Okay thank you for your explanation
