### ISSUE TITLE
Support optional function type for variables

### ISSUE THREAD

**Issue by rlinoz** [vinivendra/Gryphon#49]
**Describe the bug**
When using optional function type the result was not an optional function type, instead it was a function type with optional return in Kotlin

**How to reproduce it**
Create this code in Swift
`public var foo: (() -> ())?`

Will output this code in Kotlin
`var foo: () -> Unit? = null`

The proper result should be
`var foo: (() -> Unit)? = null`

**Your environment (please complete the following information):**
 - OS: macOS
 - Gryphon version: 0.7

**Comment by vinivendra** [comment]
Thanks for the report.
This might be an easy fix, but it's hard to say for sure. I think we're removing the parentheses when translating the type, then just not bothering to add them back (since they're usually redundant). If that's it, we can probably fix it somewhere around [here](https://github.com/vinivendra/Gryphon/blob/master/Sources/GryphonLib/KotlinTranslator.swift#L2099).
I'm not sure if this will break anything in the existing translations, we'll have to check.
