### ISSUE TITLE
Translate standard fields with regards to fields in the class

### ISSUE THREAD

**Issue by sgade** [vinivendra/Gryphon#71]
**Describe the bug**

Declaring a class with standard fields, e.g. `description`, leads to wrong translations.
Gryphon 0.9 changed some things about the templates and disregards whether there is a field named `description` in a class.

**How to reproduce it**

1. Create a `class` with a `description` field. Swift will let you do this just fine.
2. Translate using Gryphon v0.9.0.
3. Look at Kotlin output.
4. Notice the error in the constructor.

**Your environment (please complete the following information):**
 - OS: macOS 10.15.5
 - Gryphon version: 0.9.0

**Screenshots and code snippets**

Original source: 
```swift
class Event {
  let title: String
  let description: String

  init(title: String, description: String {
    self.title = title
    self.description = description
  }
}
```

Translated using 0.9 (see last line in the `constructor`):
```kotlin
open class Event {
    val title: String
    val description: String

    constructor(
        title: String,
        description: String)
    {
        this.title = title
        this.toString() = description
   }
}
```

`this.toString() = description` should instead be `this.description = description`.

**Comment by vinivendra** [comment]
Good catch. I _think_ we can fix this by keeping track of what protocols each class implements in the `TemplateContext`, then using that to only translate as `toString` if the class conforms to `CustomStringConvertible`.

If you want to submit a PR for this issue (or any others), feel free to assign it to yourself. Otherwise, I'll try to fix them later today.

**Comment by sgade** [comment]
Sounds plausible. I have to admin that the code intimidates me a bit at the moment. Also, I was not able to find the `TemplateContext`. So I'm not really sure where to start, but I'd love to submit a PR.

Do you mean the `TranspilationContext`? I found that at the location where I think `toString` method implementations are translated.

**Comment by vinivendra** [comment]
> Do you mean the `TranspilationContext`?

Yeah I did, sorry 😅

> the code intimidates me a bit at the moment

No problems, I'm here to help. The more I think about it, though, the more it seems like this is gonna be a complicated one to fix; you might prefer to start by fixing #69 or raising the warnings in #70, which will probably be easier.

Here's what I'd do:

- [ ] In the `TranspilationContext`, create a variable to store type names and their inheritances. Maybe call it something like `inheritances`, and make it similar to the `protocols` variable. I think it might be something like a `MutableMap<String, List<String>>`, to map the type to its inheritances, but feel free to use whatever you think is best.

- [ ] In `TranspilationPass.swift`, create a new class, maybe similar to `RecordEnumsTranspilationPass`. Override `replaceEnumDeclaration`, `replaceStructDeclaration`, and `replaceClassDeclaration`, and use each of these methods to add the inheritances to the `transpilationContext.inheritances` you created earlier.

- [ ] The `description` variables are translated according to templates defined in the `.gryphon/GryphonTemplatesLibrary.swift` file. In that file, you can create a new `_CustomStringConvertible` type that conforms to `CustomStringConvertible` (look at how the `_Hashable` and `_Any` types are declared for reference). Then, update the `description` template (the `_ = _anyType.description` below) to use your new type.

- [ ] Copy your changes to the `.gryphon/GryphonTemplatesLibrary.swift` file over to `AuxiliaryFileContents.swift`, otherwise they'll be erased.

- [ ] Finally, go to `LibraryTranspilationPass.swift`, find the `String.isSubtype(of:)` method, and use the `transpilationContext.inheritances` variable to check if the type inherits from `CustomStringConvertible` whenever you find a `_CustomStringConvertible` type.

Like I said, it's complicated, so feel free to ask for help.

**Comment by sgade** [comment]
Thanks for the fix! I wouldn't have gotten it done nearly as quickly as you did. 👍

**Comment by vinivendra** [comment]
Hey, I've been working on this full-time for three years now, don't feel bad about it 😄
